### ISSUE TITLE
Esqueleto-compatible upsert

### ISSUE THREAD

**Issue by tysonzero** [bitemyapp/esqueleto#131] opened 2019-08-08 23:08 UTC
Currently `upsert` is re-exported from Persistent, and it takes in a list of Persistent `Update` values, which is awkward to use alongside esqueleto as the type and operator names collide with Esqueleto's `Update`.

This means if you are using Esqueleto and want to do an upsert, you are going to need to either use qualified imports, or use multiple queries.

It would be nice if esqueleto instead defined its own upsert.

**Comment by bitemyapp** [comment] 2019-09-24 14:41
I think this is a duplicate of #56.

**Comment by parsonsmatt** [comment] 2019-10-28 16:30
I believe this will be fixed by #155

**Closed** 2024-12-27 19:08 UTC
Labels: enhancement
