### ISSUE TITLE
No docs for 3.3.4.0 on Hackage

### ISSUE THREAD

**Issue by googleson78** [bitemyapp/esqueleto#207] opened 2020-09-24 15:11 UTC
There are no docs for esqueleto 3.3.4.0 on Hackage - https://hackage.haskell.org/package/esqueleto-3.3.4.0

Is this the right place to be reporting this? Sorry if it isn't!

**Comment by jkachmar** [comment] 2020-10-09 02:59
Looks like Hackage doesn’t provide any additional context as to why Haddock generation failed:

https://hackage.haskell.org/package/esqueleto-3.3.4.0/reports/3

**Comment by googleson78** [comment] 2020-10-09 07:27
It generates haddock fine locally with cabal too :thinking:

**Comment by belevy** [comment] 2020-10-27 01:55
This appears to have been caused by the re-export of `Database.Esqueleto` from `Database.Esqueleto.Experimental`. This is fixed by #215 though 3.3.4.0 will not have docs in that case.

**Closed** 2020-10-29 03:37 UTC
