### ISSUE TITLE
Bump version bounds to be compatible with `persistent-2.8.x`

### ISSUE THREAD

**Issue by thomasjm** [bitemyapp/esqueleto#78] opened 2018-03-14 02:16 UTC
I'd love to switch to the new Stackage LTS-11.0, but Esqueleto isn't there because it's incompatible with the new `persistent`. An upgrade would be much appreciated. See also https://github.com/fpco/stackage/issues/3255

**Comment by bitemyapp** [comment] 2018-03-14 04:58
Me too! I'd like to sort out compatibility with read-write roles first. This includes tests ensuring the correct things type-check and the correct things do _not_ type-check, such as an attribution of a read-only type to an insert, delete, or update.

To that end, I've already been working on this! See this branch here: https://github.com/bitemyapp/esqueleto/tree/bitemyapp/validate-read-write-roles

Any help would be greatly appreciated but it's also a bit of a mess so if this is anything you're interested in you should give me a ping so I can brief you on what's needed.

**Comment by ChrisCoffey** [comment] 2018-04-19 01:33
I could use this as well & may take a stab at it in the next week or two. Is your read/write roles branch the best place to get an overview of your progress?

**Comment by bitemyapp** [comment] 2018-04-19 01:38
@ChrisCoffey that plus possibly also this https://github.com/bitemyapp/esqueleto/pull/83

Executive summary IMO is: abandon the `should-not-typecheck` library as the behavior it relies on is flaky. Rewrite as a shell script that ensures the exit code and error look approximately okay.

Please keep me posted even if it's to say you're pulling off of it. Thank you!

**Comment by peti** [comment] 2018-07-10 12:03
Ping? I wonder what the state of this PR is?

**Comment by ChrisCoffey** [comment] 2018-07-10 17:53
Unfortunately I never got around to cleaning up the read-write role tests, nor does it look like I'll be able to anytime soon.

**Comment by clinty** [comment] 2018-07-10 17:55
Then perhaps blocking the release for that isn't the best.

**Comment by bitemyapp** [comment] 2018-07-10 18:01
@ChrisCoffey I'd kicked that around since then, I just haven't had a lot of free time for moving toward a release soon and nobody else has picked the ball up either.

>Then perhaps blocking the release for that isn't the best.

I cut releases when I believe they're release-ready. You can [use a SHA1 package](https://github.com/lorepub/moot/blob/master/stack.yaml#L5-L8) in a `stack.yaml` until then if you don't care about that.

This is the tracking branch I believe: https://github.com/bitemyapp/esqueleto/tree/bitemyapp/validate-read-write-roles

**Comment by thomasjm** [comment] 2018-08-25 00:57
Question, is this read-write role stuff a new feature or a fix to the existing version? If it's the former, I think it would be better to cut the compatibility release you mentioned above. Esqueleto is absent from Stackage `lts-11` and `lts-12` now, and it's the main thing keeping me from upgrading.

This goes especially if it's a relatively simple matter to get an `lts-11` or `lts-12` compatible version out (bumping version bounds/small fixes). If that's the case I can take a stab at it myself. What do you think?

**Comment by thomasjm** [comment] 2018-10-02 03:33
@bitemyapp friendly ping on the above question :)

**Comment by bitemyapp** [comment] 2018-10-02 05:39
It's a fix to already released functionality.

**Comment by parsonsmatt** [comment] 2018-12-18 21:34
Closing as duplicate of #89 and #109

**Closed by parsonsmatt** 2018-12-18 21:34 UTC
