### ISSUE TITLE
Get esqueleto back into Stackage (LTS 11 or 12)

### ISSUE THREAD

**Issue by CaptJakk** [bitemyapp/esqueleto#105] opened 2018-10-18 16:37 UTC
I love this library and would love to be able to use it with newer versions of GHC and associated libraries, last I checked we needed to make some updates to this to get it there. I'm opening this issue thread to document the process of getting it updated. This does not by any means require input, although input from existing maintainers is very welcome and encouraged.

**Comment by bitemyapp** [comment] 2018-10-18 17:02
Cf.

- https://github.com/bitemyapp/esqueleto/issues/104#issuecomment-429986072
- https://github.com/bitemyapp/esqueleto/issues/89
- https://github.com/bitemyapp/esqueleto/issues/88#issuecomment-393195660
- https://github.com/bitemyapp/esqueleto/issues/80

You can pin a SHA1 for now. If you fix it to work with newer a GHC or Persistent version, please PR it.

I won't push a release to Hackage without a better correctness and testing story in place.

**Comment by CaptJakk** [comment] 2018-10-18 17:03
Yeah we currently pin the sha1 in production, but I think it'd still be nice to get back into hackage/stackage. I'll see if I can beef up the correctness/testing, and would love to get some input on the PR. Do you have an idea of what you would like to see? or just "better"?

**Comment by bitemyapp** [comment] 2018-10-18 17:09
@CaptJakk Did you look at this issue https://github.com/bitemyapp/esqueleto/issues/89 ?

It's everything related to the read/write roles. They weren't correct before and there need to be tests validating that stuff fails properly. I got a head start on it in the branch but I don't believe it's complete or that the whole API has the appropriate annotations.

When it's complete I can test the library against client code privately to see if it breaks anything.

**Comment by CaptJakk** [comment] 2018-10-18 17:11
Cool, I'll take a look at that.

**Comment by joeyh** [comment] 2018-11-05 17:58
Does it really make sense to tie together a new correctness requirement with supporting the newer haskell ecosystem? Is there any actual connection between the two?

For perspective, I've just gotten a patch from a linux distribution to make my program build using persistent alone, rather than esquelito, because this is causing them sufficient pain it was worth developing that.

**Comment by parsonsmatt** [comment] 2018-12-18 21:03
@joeyh The idea is to not release broken code. It doesn't *really* support the new Haskell ecosystem if it doesn't actually work :)

If folks have existence-proofs that the `master` branch works on their project, we'd love to see them!

**Comment by parsonsmatt** [comment] 2018-12-18 21:36
Closing as duplicate of #89 and #109

**Closed by parsonsmatt** 2018-12-18 21:36 UTC
