### ISSUE TITLE
Hackage release to match nixpkgs release

### ISSUE THREAD

**Issue by tysonzero** [bitemyapp/esqueleto#104] opened 2018-10-15 19:23 UTC
It looks like nixpkgs points to version 2.6.0 of esqueleto after [this](https://github.com/NixOS/nixpkgs/commit/dcd037c14aabfa879a92eb15556dd7208f8ed50a) commit, even though it is not on hackage. This isn't a huge deal but it makes me think that it's probably worth releasing a new Hackage version soon.

**Comment by bitemyapp** [comment] 2018-10-15 19:38
Soon as the SqlReadT/SqlWriteT/etc. stuff is fixed and there's a test suite ensuring we don't have a safety regression like that again I'll cut a release.

**Comment by parsonsmatt** [comment] 2018-12-18 21:32
I'm going to close this as a duplicate of #89 and the PR #109

**Closed by parsonsmatt** 2018-12-18 21:32 UTC
