### ISSUE TITLE
Support for persistent-2.8.1?

### ISSUE THREAD

**Issue by peti** [bitemyapp/esqueleto#80] opened 2018-03-20 18:21 UTC
Current versions of Stackage have updated to version 2.8.x of the persistent library. Would it be possible to get a new release that supports those newer versions?

**Comment by bitemyapp** [comment] 2018-03-20 18:34
Cf. https://github.com/bitemyapp/esqueleto/issues/78

It's possible, but my priority is on fixing the type-safety issues.

**Comment by clinty** [comment] 2018-04-18 01:29
Any commit in particular?

**Comment by bitemyapp** [comment] 2018-04-18 01:39
@clinty I didn't have one in particular in mind, did latest on `master` not work?

**Comment by clinty** [comment] 2018-04-18 12:03
It seems to work.

**Comment by peti** [comment] 2018-07-10 12:04
Will there be a new version that fixes this issue?

**Comment by parsonsmatt** [comment] 2018-12-18 21:35
Closing as duplicate of #89 and #109

**Closed by parsonsmatt** 2018-12-18 21:35 UTC
